### ISSUE TITLE
module kombu.async not found 

### ISSUE THREAD

**Issue by ecomovement** [douglasmiranda/docker-taiga#14]
```
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/bin/celery", line 11, in <module>
celeryworker_1  |     sys.exit(main())
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 12, in main
celeryworker_1  |     maybe_patch_concurrency()
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/__init__.py", line 146, in maybe_patch_concurrency
celeryworker_1  |     concurrency.get_implementation(pool)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/__init__.py", line 23, in get_implementation
celeryworker_1  |     return symbol_by_name(cls, ALIASES)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
celeryworker_1  |     module = imp(module_name, package=package, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celeryworker_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
celeryworker_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
celeryworker_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/concurrency/gevent.py", line 4, in <module>
celeryworker_1  |     from kombu.async import timer as _timer
celeryworker_1  | ModuleNotFoundError: No module named 'kombu.async'
```

**Comment by notFloran** [comment]
I find the following issue: https://github.com/celery/celery/issues/4749

I fix the doker image with this: https://github.com/ter-informatique/docker-taiga/commit/8ea5db6d255e1b090f30116b8f4f6d3df7ab1f5f
